argparse_cfg:
  gpus:
    bind_to: processor_cfg.gpus
    help: number of gpus
  batch_size:
    bind_to: processor_cfg.batch_size
  checkpoint:
    bind_to: processor_cfg.checkpoint
    help: the checkpoint file to load from
    default: /home/hentschel/visual-gesture-recognition/action_recognition/mmskeleton/work_dir/recognition/st_gcn_aaai18/gestures/epoch_50.pth

processor_cfg:
  type: "processor.recognition.test"
  checkpoint:

  # model setting
  model_cfg:
    type: "models.backbones.ST_GCN_AAAI18"
    in_channels: 3
    num_class: 3
    edge_importance_weighting: True
    graph_cfg:
      layout: "openpose"
      strategy: "spatial"

  # dataset setting
  dataset_cfg:
    type: "deprecated.datasets.skeleton_feeder.SkeletonFeeder"
    data_path: ./data/gestures/val_data.npy
    label_path: ./data/gestures/val_label.pkl
    # debug: true

  # dataloader setting
  batch_size: 3
  gpus: 1
